import { Product, ShopProfile } from './types';

export const DEFAULT_SHOP_PROFILE: ShopProfile = {
  shopName: 'Tirumala Milk Parlour',
  franchiseBrand: 'Tirumala Dairy Outlet',
  tagline: 'Fresh Milk & Pure Dairy Products • Chennai',
  contactNumber: '+91 98400 12345',
  currencySymbol: '₹',
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-fcm-1000ml',
    name: 'FCM Homogenized Milk Sachet 1000 ML',
    tamilName: 'FCM ஹோமோஜெனைஸ்டு பால் 1000 மிலி',
    category: 'Milk',
    unit: '1000 ML sachet',
    price: 74.00,
    wholesalePrice: 70.00,
    wholesaleCrateSize: 12,
    isActive: true,
    sortOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-curd-tm-cup-180g',
    name: 'Curd T.M. Plastic Cup 180 GMS',
    tamilName: 'தயிர் T.M. பிளாஸ்டிக் கப் 180 கிராம்',
    category: 'Curd & Dairy',
    unit: '180 GMS cup',
    price: 14.29,
    wholesalePrice: 13.00,
    wholesaleCrateSize: 24,
    isActive: true,
    sortOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-dt-milk-500ml',
    name: 'Double Toned Milk 500 ML',
    tamilName: 'டபுள் டோன்ட் பால் 500 மிலி',
    category: 'Milk',
    unit: '500 ML pouch',
    price: 42.00,
    wholesalePrice: 39.00,
    wholesaleCrateSize: 20,
    isActive: true,
    sortOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-fcm-500ml',
    name: 'FCM Homogenized Milk Sachet 500 ML',
    tamilName: 'FCM ஹோமோஜெனைஸ்டு பால் 500 மிலி',
    category: 'Milk',
    unit: '500 ML sachet',
    price: 76.00,
    wholesalePrice: 72.00,
    wholesaleCrateSize: 20,
    isActive: true,
    sortOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-fcm-110ml',
    name: 'FCM Homogenized Milk Sachet 110 ML',
    tamilName: 'FCM ஹோமோஜெனைஸ்டு பால் 110 மிலி',
    category: 'Milk',
    unit: '110 ML sachet',
    price: 8.45,
    wholesalePrice: 7.80,
    wholesaleCrateSize: 40,
    isActive: true,
    sortOrder: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-lassi-160ml',
    name: 'Lassi Pouch 160 ML',
    tamilName: 'லஸ்ஸி பாக்கெட் 160 மிலி',
    category: 'Beverages',
    unit: '160 ML pouch',
    price: 7.62,
    wholesalePrice: 7.00,
    wholesaleCrateSize: 30,
    isActive: true,
    sortOrder: 6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-curd-tm-sachet-110g',
    name: 'Curd T.M. Sachet 110 GMS (Thick)',
    tamilName: 'தயிர் T.M. பாக்கெட் 110 கிராம் (கெட்டி)',
    category: 'Curd & Dairy',
    unit: '110 GMS sachet',
    price: 7.90,
    wholesalePrice: 7.20,
    wholesaleCrateSize: 40,
    isActive: true,
    sortOrder: 7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-thirumala-family-450ml',
    name: "Thirumala Family's Choice Milk 450 ML",
    tamilName: 'திருமலா ஃபேமிலிஸ் சாய்ஸ் பால் 450 மிலி',
    category: 'Milk',
    unit: '450 ML pouch',
    price: 30.43,
    wholesalePrice: 28.00,
    wholesaleCrateSize: 20,
    isActive: true,
    sortOrder: 8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-standardised-milk-1l',
    name: 'Standardised Milk Pack 1 LT (5.5%–9.5%)',
    tamilName: 'ஸ்டாண்டர்டைஸ்டு பால் பாக்கெட் 1 லிட்டர்',
    category: 'Milk',
    unit: '1 LT pack',
    price: 67.00,
    wholesalePrice: 63.00,
    wholesaleCrateSize: 12,
    isActive: true,
    sortOrder: 9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
