import { Product, ShopProfile } from './types';

export const DEFAULT_SHOP_PROFILE: ShopProfile = {
  shopName: 'Tirumala Milk Parlour',
  franchiseBrand: 'Tirumala Dairy Outlet',
  tagline: 'Fresh Milk & Pure Dairy Products • Chennai',
  contactNumber: '+91 98400 12345',
  currencySymbol: '₹',
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-toned-milk',
    name: 'Toned Milk (Green)',
    tamilName: 'டோன்ட் பால்',
    category: 'Milk',
    unit: '500ml pouch',
    price: 24,
    wholesalePrice: 22,
    wholesaleCrateSize: 20,
    isActive: true,
    sortOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-standard-milk',
    name: 'Standardised Milk (Orange)',
    tamilName: 'சத்துப்பால்',
    category: 'Milk',
    unit: '500ml pouch',
    price: 27,
    wholesalePrice: 25,
    wholesaleCrateSize: 20,
    isActive: true,
    sortOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-fcm-milk',
    name: 'Full Cream Milk (Blue)',
    tamilName: 'முழு பாலேடு பால்',
    category: 'Milk',
    unit: '500ml pouch',
    price: 33,
    wholesalePrice: 30.5,
    wholesaleCrateSize: 20,
    isActive: true,
    sortOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-curd-pouch',
    name: 'Fresh Curd Pouch',
    tamilName: 'தயிர் பாக்கெட்',
    category: 'Curd & Dairy',
    unit: '450g pouch',
    price: 35,
    wholesalePrice: 32,
    wholesaleCrateSize: 15,
    isActive: true,
    sortOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-curd-cup',
    name: 'Fresh Curd Cup',
    tamilName: 'தயிர் கப்',
    category: 'Curd & Dairy',
    unit: '200g cup',
    price: 20,
    wholesalePrice: 18,
    wholesaleCrateSize: 24,
    isActive: true,
    sortOrder: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-buttermilk',
    name: 'Spiced Buttermilk (Moru)',
    tamilName: 'மோர்',
    category: 'Beverages',
    unit: '180ml tetra/pouch',
    price: 12,
    wholesalePrice: 10,
    wholesaleCrateSize: 30,
    isActive: true,
    sortOrder: 6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-lassi-sweet',
    name: 'Sweet Lassi',
    tamilName: 'இனிப்பு லஸ்ஸி',
    category: 'Beverages',
    unit: '160ml cup',
    price: 25,
    wholesalePrice: 22,
    wholesaleCrateSize: 20,
    isActive: true,
    sortOrder: 7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-lassi-mango',
    name: 'Mango Lassi',
    tamilName: 'மாம்பழ லஸ்ஸி',
    category: 'Beverages',
    unit: '160ml cup',
    price: 30,
    wholesalePrice: 26,
    wholesaleCrateSize: 20,
    isActive: true,
    sortOrder: 8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-flavoured-milk',
    name: 'Flavoured Milk (Badam/Pista)',
    tamilName: 'பாதாம் பால்',
    category: 'Beverages',
    unit: '180ml glass bottle',
    price: 35,
    wholesalePrice: 30,
    wholesaleCrateSize: 24,
    isActive: true,
    sortOrder: 9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-pure-ghee-1l',
    name: 'Pure Cow Ghee',
    tamilName: 'பசு நெய்',
    category: 'Ghee & Fats',
    unit: '1 Litre jar',
    price: 650,
    wholesalePrice: 590,
    wholesaleCrateSize: 6,
    isActive: true,
    sortOrder: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-pure-ghee-500ml',
    name: 'Pure Cow Ghee',
    tamilName: 'பசு நெய்',
    category: 'Ghee & Fats',
    unit: '500ml jar',
    price: 340,
    wholesalePrice: 310,
    wholesaleCrateSize: 12,
    isActive: true,
    sortOrder: 11,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-paneer-500g',
    name: 'Fresh Paneer Block',
    tamilName: 'பன்னீர்',
    category: 'Paneer & Sweets',
    unit: '500g vacuum pack',
    price: 220,
    wholesalePrice: 195,
    wholesaleCrateSize: 10,
    isActive: true,
    sortOrder: 12,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-paneer-200g',
    name: 'Fresh Paneer Block',
    tamilName: 'பன்னீர்',
    category: 'Paneer & Sweets',
    unit: '200g vacuum pack',
    price: 100,
    wholesalePrice: 88,
    wholesaleCrateSize: 20,
    isActive: true,
    sortOrder: 13,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-icecream-vanilla',
    name: 'Classic Vanilla Ice Cream',
    tamilName: 'வெண்ணிலா ஐஸ்கிரீம்',
    category: 'Ice Cream',
    unit: '100ml cup',
    price: 25,
    wholesalePrice: 20,
    wholesaleCrateSize: 30,
    isActive: true,
    sortOrder: 14,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-icecream-kulfi',
    name: 'Malai Kulfi / Chocobar',
    tamilName: 'குல்பி / சாக்கோபார்',
    category: 'Ice Cream',
    unit: 'Stick / Bar',
    price: 30,
    wholesalePrice: 24,
    wholesaleCrateSize: 25,
    isActive: true,
    sortOrder: 15,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
